# Trime专用配置
# encoding: utf-8

config_version: "0.36"

ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Caps_Lock: clear
    Control_L: noop
    Control_R: noop
    Eisu_toggle: clear
    Shift_L: inline_ascii
    Shift_R: commit_text

key_binder:
  bindings:
    ## Emacs风格按键
     # - {accept: "Control+p", send: Up, when: composing}
    # - {accept: "Control+n", send: Down, when: composing}
    # - {accept: "Control+b", send: Left, when: composing}
    # - {accept: "Control+f", send: Right, when: composing}
    # - {accept: "Control+a", send: Home, when: composing}
    # - {accept: "Control+e", send: End, when: composing}
    # - {accept: "Control+d", send: Delete, when: composing}
    # - {accept: "Control+k", send: "Shift+Delete", when: composing}
    # - {accept: "Control+h", send: BackSpace, when: composing}
    # - {accept: "Control+g", send: Escape, when: composing}
    # - {accept: "Control+bracketleft", send: Escape, when: composing}
    # - {accept: "Alt+v", send: Page_Up, when: composing}
    # - {accept: "Control+v", send: Page_Down, when: composing}
    # - {accept: ISO_Left_Tab, send: Page_Up, when: composing}
    # - {accept: "Shift+Tab", send: Page_Up, when: composing}
    # - {accept: Tab, send: Page_Down, when: composing}
    ## 前后翻页，-/=、,/.
    - {accept: minus, send: Page_Up, when: has_menu}
    - {accept: equal, send: Page_Down, when: has_menu}
    - {accept: comma, send: Page_Up, when: has_menu}
    - {accept: period, send: Page_Down, when: has_menu}
    ## Ctrl+Shift的快捷键
    # Ctrl+Shift+1、Ctrl+Shift+!: 下一个方案
    - {accept: "Control+Shift+1", select: .next, when: always}
    - {accept: "Control+Shift+exclam", select: .next, when: always}
    # Ctrl+Shift+2、Ctrl+Shift+@: 中/英
    - {accept: "Control+Shift+2", toggle: ascii_mode, when: always}
    - {accept: "Control+Shift+at", toggle: ascii_mode, when: always}
    # Ctrl+Shift+3、Ctrl+Shift+#、Shift+空格: 全角/半角
    - {accept: "Control+Shift+3", toggle: full_shape, when: always}
    - {accept: "Control+Shift+numbersign", toggle: full_shape, when: always}
    - {accept: "Shift+space", toggle: full_shape, when: always}
    # Ctrl+Shift+4、Ctrl+Shift+$: 简/繁
    - {accept: "Control+Shift+4", toggle: simplification, when: always}
    - {accept: "Control+Shift+dollar", toggle: simplification, when: always}
    # Ctrl+Shift+5、Ctrl+Shift+%: 常用/扩展
    - {accept: "Control+Shift+5", toggle: extended_charset, when: always}
    - {accept: "Control+Shift+percent", toggle: extended_charset, when: always}
    # Ctrl+.:
    - {accept: "Control+period", toggle: ascii_punct, when: always}

menu:
  page_size: 5

punctuator:
  full_shape:
    "<" : [ 《, 〈, «, ‹ ]
    ">" : [ 》, 〉, », › ]
    "/" : [ ／, ÷ ]
    "?" : { commit: ？ }
    ";" : { commit: ； }
    ":" : { commit: ： }
    """" : { pair: [ "‘", "’" ] }
    """ : { pair: [ "“", "”" ] }
    "\\" : [ 、, ＼ ]
    "|" : [ "·", "｜", "§", "¦" ]
    "`" : ｀
    "~" : ～
    "@" : [ ＠, ☯ ]
    "#" : [ ＃, ⌘ ]
    "%" : [ ％, "°", "℃" ]
    "$" : [ ￥, "$", "€", "£", "¥", "¢", "¤" ]
    "^" : { commit: …… }
    "&" : ＆
    "*" : [ ＊, ·, ・, ×, ※, ❂ ]
    "(" : （
    ")" : ）
    "-" : －
    "_" : ——
    "+" : ＋
    "=" : ＝
    "[" : [ 「, 【, 〔, ［ ]
    "]" : [ 」, 】, 〕, ］ ]
    "{" : [ 『, 〖, ｛ ]
    "}" : [ 』, 〗, ｝ ]
  half_shape:
    "," : { commit: ， }
    "." : { commit: 。 }
    "<" : [ 《, 〈, «, ‹ ]
    ">" : [ 》, 〉, », › ]
    "/" : [ 、, "/", ／, ÷ ]
    "?" : { commit: ？ }
    ";" : { commit: ； }
    ":" : { commit: ： }
    """" : { pair: [ "‘", "’" ] }
    """ : { pair: [ "“", "”" ] }
    "\\" : [ 、, "\\", "＼" ]
    "|" : [ ·, "|", ｜, "§", "¦" ]
    "`" : "`"
    "~" : [ "~", ～ ]
    "!" : { commit: ！ }
    "@" : "@"
    "#" : "#"
    "%" : [ "%", ％, "°", "℃" ]
    "$" : [ "￥", "$", "€", "£", "¥", "¢", "¤" ]
    "^" : { commit: "……" }
    "&" : "&"
    "*" : [ "*", "＊", "·", "・", "×", "※", "❂" ]
    "(" : （
    ")" : ）
    "-" : "-"
    "_" : ——
    "+" : "+"
    "=" : "="
    "[" : [ 「, 【, 〔, ［ ]
    "]" : [ 」, 】, 〕,  ］ ]
    "{" : [ 『, 〖, ｛ ]
    "}" : [ 』, 〗, ｝ ]

recognizer:
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    uppercase: "[A-Z][-_+."0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"

schema_list:
  - schema: bopomofo_tw
  - schema: luna_pinyin_simp
  - schema: luna_pinyin

switcher:
  caption: 〔方案選單〕
  hotkeys:
    - Control+grave
    - Control+Shift+grave
    - F4
  save_options:
    - full_shape
    - ascii_punct
    - simplification
    - extended_charset
  fold_options: true
  abbreviate_options: true
  option_list_separator: "／"
